const DEFAULT_META_TITLE = 'ontron GmbH'

const DEFAULT_META_DESCRIPTION = ''

const DEFAULT_META_KEYWORDS = ''

const DEFAULT_META_IMAGE = ''

export default {
    DEFAULT_META_DESCRIPTION,
    DEFAULT_META_KEYWORDS,
    DEFAULT_META_TITLE,
    DEFAULT_META_IMAGE
}